<?php include_once __DIR__ . '/../../config/helpers.php'; ?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SAPHIRA - Thanh Toán</title>
    <style>
    :root { --font-display: 'Manrope', sans-serif; --font-serif: 'Cormorant Garamond', serif; --color-primary: #f4c025; --color-gold: #D4AF37; --color-bg-start: #1a1a1a; --color-bg-end: #000000; --color-header: rgba(0,0,0,0.8); --color-text-light: #ffffff; --color-text-dim: rgba(255,255,255,0.8); --color-text-dimmer: rgba(255,255,255,0.7); --color-text-placeholder: rgba(255,255,255,0.5); --color-border: rgba(255,255,255,0.2); --color-border-focus: rgba(212,175,55,0.5); --color-bg-input: rgba(255,255,255,0.05); --color-bg-input-hover: rgba(255,255,255,0.1); --color-bg-summary: rgba(0,0,0,0.5); --color-black: #000000; --border-radius: 0.5rem; --border-radius-lg: 0.75rem; --border-radius-xl: 1rem; }
    *{box-sizing:border-box;margin:0;padding:0} body{font-family:var(--font-display);background-image:linear-gradient(to bottom,var(--color-bg-start),var(--color-bg-end));color:var(--color-text-light);min-height:100vh;display:flex;flex-direction:column;overflow-x:hidden}
    a{text-decoration:none;color:inherit} button{font-family:inherit;border:none;background:none;cursor:pointer} input,select,textarea{font-family:inherit}
    .checkout-header-sticky{position:sticky;top:0;z-index:50;display:flex;align-items:center;justify-content:space-between;white-space:nowrap;border-bottom:1px solid var(--color-gold);padding:1rem;background-color:var(--color-header);backdrop-filter:blur(4px)} @media(min-width:640px){.checkout-header-sticky{padding:1rem 2rem}} @media(min-width:1024px){.checkout-header-sticky{padding:1rem 4rem}}
    .header-logo-container{display:flex;align-items:center;gap:1rem} .header-logo-text{font-family:var(--font-serif);font-size:1.25rem;font-weight:700;color:var(--color-gold);letter-spacing:.05em}
    .header-actions{display:flex;align-items:center;gap:.5rem} .icon-button{display:flex;height:2.5rem;width:2.5rem;cursor:pointer;align-items:center;justify-content:center;border-radius:9999px;color:var(--color-text-light);transition:background-color .15s ease} .icon-button:hover{background-color:var(--color-bg-input-hover)}
    .checkout-main-container{flex:1;width:100%;max-width:1280px;margin:0 auto;padding:2.5rem 1rem} @media(min-width:768px){.checkout-main-container{padding:4rem 2rem}}
    .checkout-page-header{margin-bottom:2.5rem;text-align:center} .checkout-page-title{font-family:var(--font-serif);font-size:2.25rem;font-weight:700;color:var(--color-gold);letter-spacing:.025em} @media(min-width:768px){.checkout-page-title{font-size:3rem}} .checkout-page-subtitle{margin-top:.5rem;color:var(--color-text-dim);font-size:1rem} @media(min-width:768px){.checkout-page-subtitle{font-size:1.125rem}}
    .checkout-layout-grid{display:grid;grid-template-columns:1fr;gap:2rem} @media(min-width:1024px){.checkout-layout-grid{grid-template-columns:repeat(5,1fr);gap:3rem}} .checkout-form-column{grid-column:span 1;display:flex;flex-direction:column;gap:2rem} @media(min-width:1024px){.checkout-form-column{grid-column:span 3}}
    .form-section-title{font-family:var(--font-serif);font-size:1.5rem;font-weight:700;color:var(--color-gold);margin-bottom:1rem}
    .form-grid{display:grid;grid-template-columns:1fr;gap:1rem} @media(min-width:640px){.form-grid{grid-template-columns:repeat(2,1fr)}} .col-span-2{grid-column:span 1} @media(min-width:640px){.col-span-2{grid-column:span 2}}
    .form-label{color:var(--color-text-dim);font-size:.875rem;font-weight:500;padding-bottom:.5rem;display:block} .form-input,.form-select{display:flex;width:100%;min-width:0;flex:1;resize:none;overflow:hidden;border-radius:var(--border-radius-lg);color:var(--color-text-light);background-color:var(--color-bg-input);border:1px solid var(--color-border);height:3rem;padding:.75rem;font-size:1rem;transition:all .15s ease} .form-input::placeholder,.form-select{color:var(--color-text-placeholder)} .form-input:focus,.form-select:focus{outline:none;border-color:var(--color-gold);box-shadow:0 0 0 1px var(--color-border-focus)} .form-select{appearance:none}
    .radio-group{display:flex;flex-direction:column;gap:.75rem} .radio-option,.radio-option-header{display:flex;align-items:center;padding:1rem;border-radius:var(--border-radius-lg);background-color:var(--color-bg-input);border:1px solid var(--color-border);cursor:pointer;transition:all .15s ease} .radio-option:hover,.radio-option-header:hover{background-color:var(--color-bg-input-hover)} .form-radio{height:1.25rem;width:1.25rem;background-color:var(--color-bg-input-hover);border:1px solid var(--color-border);color:var(--color-gold)} .form-radio:focus{outline:none;box-shadow:0 0 0 1px var(--color-border-focus)} .radio-option-content{margin-left:1rem;flex:1} .radio-option-content p{font-weight:600;color:var(--color-text-light)} .radio-option-content span{font-size:.875rem;color:var(--color-text-dimmer)} .radio-option-price{font-weight:600;color:var(--color-text-light)} .radio-option span{margin-left:1rem;font-weight:600;color:var(--color-text-light)} .radio-option:has(:checked),.radio-option-collapsible:has(:checked){border-color:var(--color-gold);background-color:rgba(212,175,55,0.1)} .radio-option-collapsible{border-radius:var(--border-radius-lg);background-color:var(--color-bg-input);border:1px solid var(--color-border);transition:all .15s ease} .radio-option-body{padding:0 1rem 1rem 1rem;margin-top:.5rem;border-top:1px solid var(--color-border);display:none} .radio-option-collapsible:has(:checked) .radio-option-body{display:block}
    .checkout-summary-column{grid-column:span 1} @media(min-width:1024px){.checkout-summary-column{grid-column:span 2}} .summary-box{position:sticky;top:7rem;background-color:var(--color-bg-summary);padding:1.5rem;border-radius:var(--border-radius-xl);box-shadow:0 4px 10px rgba(0,0,0,.3);border:1px solid var(--color-border);backdrop-filter:blur(12px)} @media(min-width:768px){.summary-box{padding:2rem}} .summary-title{font-family:var(--font-serif);font-size:1.5rem;font-weight:700;color:var(--color-gold);margin-bottom:1.5rem;text-align:center}
    .summary-items-list{display:flex;flex-direction:column;gap:1rem} .summary-item{display:flex;align-items:center;gap:1rem} .summary-item-image{width:4rem;height:4rem;border-radius:var(--border-radius-lg);object-fit:cover;flex-shrink:0} .summary-item-info{flex:1} .summary-item-info p{font-weight:600;color:var(--color-text-light)} .summary-item-info span{font-size:.875rem;color:var(--color-text-dimmer)} .summary-item-price{font-weight:500;color:var(--color-text-light)} .summary-divider{border-top:1px solid var(--color-border);margin:1.5rem 0}
    .summary-costs{display:flex;flex-direction:column;gap:.75rem;font-size:.875rem} .summary-cost-row{display:flex;justify-content:space-between;color:var(--color-text-dim)} .voucher-row{display:grid;grid-template-columns:1fr auto;gap:.75rem;align-items:center} .voucher-input{height:3rem} .voucher-feedback{font-size:.875rem} .voucher-feedback.success{color:var(--color-gold)} .voucher-feedback.error{color:#ff6b6b}
    .summary-total{display:flex;justify-content:space-between;align-items:center;color:var(--color-text-light)} .summary-total span:first-child{font-size:1.125rem;font-weight:600} .total-price{font-size:1.5rem;font-weight:700;color:var(--color-gold)} .form-checkbox-label.terms{margin-top:2rem} .form-checkbox-label.terms a{color:var(--color-gold)} .form-checkbox-label.terms a:hover{text-decoration:underline}
    .btn-place-order{margin-top:1.5rem;width:100%;display:flex;align-items:center;justify-content:center;height:3.5rem;border-radius:var(--border-radius-lg);background-color:var(--color-gold);color:var(--color-black);font-size:1.125rem;font-weight:700;letter-spacing:.025em;transition:opacity .15s ease, box-shadow .15s ease; box-shadow:0 4px 10px rgba(212,175,55,.2)} .btn-place-order:hover{opacity:.9}
    .btn-primary{display:inline-flex;align-items:center;justify-content:center;border-radius:var(--border-radius-lg);background-color:var(--color-gold);color:var(--color-black);font-weight:700;border:1px solid var(--color-gold);transition:opacity .15s ease, box-shadow .15s ease, background-color .15s ease; box-shadow:0 4px 10px rgba(212,175,55,.2)} .btn-primary:hover{opacity:.9} .btn-primary:focus{outline:none; box-shadow:0 0 0 1px var(--color-border-focus)}
    .btn-secondary{display:inline-flex;align-items:center;justify-content:center;border-radius:var(--border-radius-lg);background-color:transparent;color:var(--color-text-light);font-weight:600;border:1px solid var(--color-border);transition:background-color .15s ease, box-shadow .15s ease, border-color .15s ease, color .15s ease} .btn-secondary:hover{background-color:var(--color-bg-input-hover); border-color:var(--color-gold)} .btn-secondary:focus{outline:none; box-shadow:0 0 0 1px var(--color-border-focus)}
    .checkout-footer{background-color:var(--color-black);border-top:1px solid var(--color-border);margin-top:4rem;padding:1.5rem 1rem;text-align:center} .checkout-footer p{color:var(--color-text-dimmer);font-size:.875rem;max-width:1280px;margin:0 auto}
    </style>
</head>
<body>
    <header class="checkout-header-sticky"><a class="header-logo-container" href="main.php?r=home" style="display:flex;align-items:center"><div style="height:135px;width:160px;overflow:hidden;display:flex;align-items:center"><img src="<?php echo asset('img/logo/logo.png'); ?>" alt="SAPHIRA" style="height:135px;display:block" /></div></a><div class="header-actions"><a href="main.php?r=cart" class="icon-button" title="Giỏ hàng"><span class="material-symbols-outlined">shopping_bag</span></a><a href="main.php?r=account" class="icon-button" title="Tài khoản"><span class="material-symbols-outlined">person</span></a></div></header>
